apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-mcp-server
spec:
  template:
    spec:
      containers:
      - name: flux-mcp-server
        # Use IfNotPresent for local development (images loaded into kind)
        imagePullPolicy: IfNotPresent
        # Reduce resources for local development
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"

