apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-job-results
  namespace: slurm
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pods to read/write
  resources:
    requests:
      storage: 10Gi
  # For kind cluster, this will use local-path provisioner
  # In production, use NFS or similar shared storage

