apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-operator

bases:
  - ../../base

# Override images for local development
images:
  - name: quay.io/kugupta/flux-mcp-server
    newName: localhost/flux-mcp-server
    newTag: latest

# Patches for local development
patches:
  - path: patches/deployment-local.yaml
    target:
      kind: Deployment
      name: flux-mcp-server

