apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-mcp-server
  namespace: flux-operator
  labels:
    app: flux-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-mcp-server
  template:
    metadata:
      labels:
        app: flux-mcp-server
    spec:
      containers:
      - name: flux-mcp-server
        image: quay.io/kugupta/flux-mcp-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: mcp
          protocol: TCP
        env:
        - name: FLUX_URI
          value: "local:///mnt/flux/view/run/flux/local"
        - name: FLUX_NAMESPACE
          value: "flux-operator"
        - name: FLUX_MINICLUSTER
          value: "flux-sample"
        - name: MCP_PORT
          value: "5001"
        - name: MCP_HOST
          value: "0.0.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: kube-api-access
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      serviceAccountName: flux-mcp-sa
      volumes:
      - name: kube-api-access
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
          - downwardAPI:
              items:
              - path: namespace
                fieldRef:
                  fieldPath: metadata.namespace

