apiVersion: v1
kind: Namespace
metadata:
  name: slurm
  labels:
    app.kubernetes.io/part-of: hpc-mcp
    workload-type: slurm
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

