apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/flux-framework/flux-operator.git
    targetRevision: main
    path: examples/dist
  destination:
    server: https://kubernetes.default.svc
    namespace: operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

