apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-mcp-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kush-gupt/sc25.git
    targetRevision: HEAD
    path: manifests/flux-mcp-server/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: flux-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

