apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm-operator-crds
    targetRevision: 0.4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false  # Don't prune CRDs automatically
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

